### ISSUE TITLE
ImportError: cannot import name generic 

### ISSUE THREAD

**Issue by DandyCoder** [llazzaro/django-scheduler#166]
Hello, 

I'm adding on the scheduler to an existing project of mine as an app. 

However, after install through pip and adding to the installed apps in my settings, I'm getting the following:

Unhandled exception in thread started by <function wrapper at 0x7f5fe962d8c0>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/schedule/models/__init__.py", line 1, in <module>
    from schedule.models.calendars import *
  File "/usr/local/lib/python2.7/dist-packages/schedule/models/calendars.py", line 8, in <module>
    from django.contrib.contenttypes import generic
ImportError: cannot import name generic

I'm using django1.9 and nothing mentions that generic has been removed from the contenttypes. 

Can't figure out what's causing this. 

Would it just be better to use django 1.8?

**Comment by llazzaro** [comment]
the current version on pypi is not compatible with django 1.9.
you could try to install the dev version with pip install git+https://github.com/llazzaro/django-scheduler.git

remeber that you are installing the dev version of scheduler.

**Comment by DandyCoder** [comment]
Thank you. I only discovered this morning that this was moved in 1.9 completely. Which explains everything! 

I'll close this.
