### ISSUE TITLE
Event.objects.all() gives error in ./manage.py shell

### ISSUE THREAD

**Issue by gabn88** [llazzaro/django-scheduler#168]
>>> Event.objects.all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/Desktop/test_django_scheduler/django-scheduler-sample-master/lib/python3.4/site-packages/django/db/models/query.py", line 141, in __repr__
    return repr(data)
  File "/home/Desktop/test_django_scheduler/django-scheduler-sample-master/lib/python3.4/site-packages/django/db/models/base.py", line 496, in __repr__
    u = six.text_type(self)
  File "/home/Desktop/test_django_scheduler/django-scheduler-sample-master/src/django-scheduler/schedule/models/events.py", line 61, in __str__
    'start': date(self.start, django_settings.DATE_FORMAT),
  File "/home/Desktop/test_django_scheduler/django-scheduler-sample-master/lib/python3.4/site-packages/django/template/defaultfilters.py", line 771, in date
    return formats.date_format(value, arg)
  File "/home/Desktop/test_django_scheduler/django-scheduler-sample-master/lib/python3.4/site-packages/django/utils/formats.py", line 136, in date_format
    return dateformat.format(value, get_format(format or 'DATE_FORMAT', use_l10n=use_l10n))
  File "/home/Desktop/test_django_scheduler/django-scheduler-sample-master/lib/python3.4/site-packages/django/utils/formats.py", line 110, in get_format
    for module in get_format_modules(lang):
  File "/home/Desktop/test_django_scheduler/django-scheduler-sample-master/lib/python3.4/site-packages/django/utils/formats.py", line 82, in get_format_modules
    modules = _format_modules_cache.setdefault(lang, list(iter_format_modules(lang, settings.FORMAT_MODULE_PATH)))
  File "/home/Desktop/test_django_scheduler/django-scheduler-sample-master/lib/python3.4/site-packages/django/utils/formats.py", line 51, in iter_format_modules
    if not check_for_language(lang):
  File "/home/Desktop/test_django_scheduler/django-scheduler-sample-master/lib/python3.4/site-packages/django/utils/translation/__init__.py", line 181, in check_for_language
    return _trans.check_for_language(lang_code)
  File "/home/Desktop/test_django_scheduler/django-scheduler-sample-master/lib/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "/home/Desktop/test_django_scheduler/django-scheduler-sample-master/lib/python3.4/site-packages/django/utils/translation/trans_real.py", line 409, in check_for_language
    if not language_code_re.search(lang_code):
TypeError: expected string or buffer

Seems to be an issue with language or DATE_FORMAT or so. On Python3.4.3 with django 1.8. 

See also the issue created here: https://github.com/llazzaro/django-scheduler-sample/issues/11

**Comment by gabn88** [comment]
Issue seems to be resolved in Django 1.8.8!
