### ISSUE TITLE
Model instances without primary key value are unhashable

### ISSUE THREAD

**Issue by gabn88** [llazzaro/django-scheduler#170]
Trying out the well written help I get the following error with the Event.get_occurences method, if I do:

>event = Event(start=datetime.datetime(2008,1,1,8,0), end=datetime.datetime(2008,1,1,9,0))
         occurrences = event.get_occurrences(datetime.datetime(2008,1,1), datetime.datetime(2008,3,2))

>>Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/gerben/Desktop/test_django_scheduler/django-scheduler-sample-master/src/django-scheduler/schedule/models/events.py", line 105, in get_occurrences
    if occ_replacer.has_occurrence(occ):
  File "/home/gerben/Desktop/test_django_scheduler/django-scheduler-sample-master/src/django-scheduler/schedule/utils.py", line 85, in has_occurrence
    return (occ.event, occ.original_start, occ.original_end) in self.lookup
  File "/home/gerben/Desktop/test_django_scheduler/django-scheduler-sample-master/lib/python3.4/site-packages/django/db/models/base.py", line 521, in __hash__
    raise TypeError("Model instances without primary key value are unhashable")
TypeError: Model instances without primary key value are unhashable

**Comment by gabn88** [comment]
Fixed by https://github.com/llazzaro/django-scheduler/pull/171
