### ISSUE TITLE
debugg

### ISSUE THREAD

**Issue by Belaswan** [llazzaro/django-scheduler#252]
Traceback (most recent call last):
  File "/usr/lib/pycharm/helpers/pycharm/django_test_manage.py", line 53, in <module>
    django.setup()
  File "/home/manorama/anaconda/envs/zero/lib/python3.5/site-packages/django/**init**.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/manorama/anaconda/envs/zero/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/manorama/anaconda/envs/zero/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/manorama/anaconda/envs/zero/lib/python3.5/importlib/**init**.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/manorama/anaconda/envs/zero/lib/python3.5/site-packages/django_schedule-0.5b0-py3.5.egg/schedule/models/__init__.py", line 1, in <module>
    from schedule.models.calendars import *
  File "/home/manorama/anaconda/envs/zero/lib/python3.5/site-packages/django_schedule-0.5b0-py3.5.egg/schedule/models/calendars.py", line 12, in <module>
    from schedule.utils import EventListManager
  File "/home/manorama/anaconda/envs/zero/lib/python3.5/site-packages/django_schedule-0.5b0-py3.5.egg/schedule/utils.py", line 6, in <module>
    from schedule.conf.settings import CHECK_PERMISSION_FUNC
ImportError: No module named 'schedule.conf'

Process finished with exit code 1

 how to resolve it??

**Comment by llazzaro** [comment]
@Belaswan you are using https://github.com/thauber/django-schedule this project is django-scheduler, which is a fork of django-schedule.
We added fixes to the original project but you error is too old and probably.
Try install django-scheduler instead.
