### ISSUE TITLE
Not able to set SCHEDULER_BASE_CLASSES

### ISSUE THREAD

**Issue by mjramos-mahi** [llazzaro/django-scheduler#310]
Hey @llazzaro I'm trying to configure the SCHEDULER_BASE_CLASSES settings in my settings.py as follows:

```python
SCHEDULER_BASE_CLASSES = {
    'Event': ['my_app.models.MyAppEvent']
}
```

but I'm getting this error: 
>'Event' doesn't look like a module path

Is there something I'm missing here?

**Comment by llazzaro** [comment]
do you have any stack trace?

**Comment by mjramos-mahi** [comment]
Thanks for the prompt response. Here the stack trace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/utils/module_loading.py", line 15, in import_string
    module_path, class_name = dotted_path.rsplit('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)
2017-04-27T16:13:34.367684235Z 
During handling of the above exception, another exception occurred:
2017-04-27T16:13:34.367759779Z 
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 192, in run
    super(Application, self).run()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 61, in __init__
    self.setup(app)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 120, in setup
    self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/usr/src/app/sundog/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.6/site-packages/schedule/models/__init__.py", line 1, in <module>
    from schedule.models.calendars import Calendar, CalendarRelation
  File "/usr/local/lib/python3.6/site-packages/schedule/models/calendars.py", line 109, in <module>
    class Calendar(with_metaclass(ModelBase, *get_model_bases())):
  File "/usr/local/lib/python3.6/site-packages/schedule/utils.py", line 242, in get_model_bases
    return [import_string(x) for x in baseStrings]
  File "/usr/local/lib/python3.6/site-packages/schedule/utils.py", line 242, in <listcomp>
    return [import_string(x) for x in baseStrings]
  File "/usr/local/lib/python3.6/site-packages/django/utils/module_loading.py", line 18, in import_string
    six.reraise(ImportError, ImportError(msg), sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/utils/module_loading.py", line 15, in import_string
    module_path, class_name = dotted_path.rsplit('.', 1)
ImportError: Event doesn't look like a module path
```
