### ISSUE TITLE
Cascade delete of event fails in django 2.2

### ISSUE THREAD

**Issue by andrlik** [llazzaro/django-scheduler#443]
Using Django >= 2.2, if you have persisted occurrences in the database they cause an error when deleting the event.

````
>>> cal = Calendar.objects.create(slug="test")
>>> event = Event.objects.create(title="An Event", calendar=cal, start=timezone.now()+timedelta(days=2), end=timezone.now()+timedelta(days=2)+timedelta(minutes=45))
>>> occurrences = event.occurrences_after(timezone.now())
>>> for o in occurrences:
            o.save()
>>> event.delete()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/daniel/.local/share/virtualenvs/lfg22tests-eyB1dCRt/lib/python3.7/site-packages/django/db/models/base.py", line 918, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/Users/daniel/.local/share/virtualenvs/lfg22tests-eyB1dCRt/lib/python3.7/site-packages/django/db/models/deletion.py", line 224, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/Users/daniel/.local/share/virtualenvs/lfg22tests-eyB1dCRt/lib/python3.7/site-packages/django/db/models/deletion.py", line 16, in CASCADE
    source_attr=field.name, nullable=field.null)
  File "/Users/daniel/.local/share/virtualenvs/lfg22tests-eyB1dCRt/lib/python3.7/site-packages/django/db/models/deletion.py", line 192, in collect
    reverse_dependency=reverse_dependency)
  File "/Users/daniel/.local/share/virtualenvs/lfg22tests-eyB1dCRt/lib/python3.7/site-packages/django/db/models/deletion.py", line 94, in add
    if obj not in instances:
TypeError: unhashable type: 'Occurrence'

**Comment by andrlik** [comment]
For some reason, Occurrence objects are all considered unhashable in Django 2.2+

On django 2.1.x:

```
>>> import collections
>>> occs = Occurrence.objects.all()
>>> occs
<QuerySet [<Occurrence: Nov. 21, 2018 to Jan. 21, 2018>, <Occurrence: Nov. 21, 2018 to Jan. 21, 2018>, <Occurrence: Nov. 21, 2018 to Jan. 21, 2018>, <Occurrence: March 12, 2019 to March 12, 2019>, <Occurrence: March 5, 2019 to March 5, 2019>, <Occurrence: March 12, 2019 to March 12, 2019>, <Occurrence: March 12, 2019 to March 12, 2019>, <Occurrence: March 5, 2019 to March 5, 2019>, <Occurrence: March 5, 2019 to March 5, 2019>, <Occurrence: March 5, 2019 to March 5, 2019>, <Occurrence: June 2, 2019 to June 2, 2019>, <Occurrence: March 5, 2019 to March 5, 2019>]>
>>> for occ in occs:
...     isinstance(occ, collections.Hashable)
...
True
True
True
True
True
True
True
True
True
True
True
True
```

On Django 2.2:

```
>>> import collections
>>> occs = Occurrence.objects.all()
>>> for occ in occs:
...     isinstance(occ, collections.Hashable)
...
False
False
False
False
False
False
False
False
False
False
False
False

**Comment by andrlik** [comment]
Appears to be related to this Django bug: https://code.djangoproject.com/ticket/30333

**Comment by andrlik** [comment]
Added a pull request to resolve the issue @llazzaro

**Comment by llazzaro** [comment]
Thanks!
