### ISSUE TITLE
issue installing on MySQL

### ISSUE THREAD

**Issue by ericjgreen** [llazzaro/django-scheduler#494]
Hi,
I've attempted to setup a base project, base app, setup my settings.py, and attempted to run migrations. I have nothing in this project except changes to settings.py to connect to my backend MySQL, installed (via pip) the django-scheduler, added schedule to the installed apps, run makemigrations and attempted to migrate. Upon executing this, i get an error as noted below
```
`PS C:\Development\Django\TestProject\src> python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, schedule, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying schedule.0001_initial... OK
  Applying schedule.0002_event_color_event... OK
  Applying schedule.0003_auto_20160715_0028... OK
  Applying schedule.0006_update_text_fields_empty_string... OK
  Applying schedule.0004_text_fields_not_null...Traceback (most recent call last):
  File "C:\Development\Django\TestProject\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Development\Django\TestProject\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "C:\Development\Django\TestProject\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Development\Django\TestProject\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Development\Django\TestProject\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1101, "BLOB, TEXT, GEOMETRY or JSON column 'description' can't have a default value")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Development\Django\TestProject\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Development\Django\TestProject\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Development\Django\TestProject\lib\site-packages\django\core\management\base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Development\Django\TestProject\lib\site-packages\django\core\management\base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "C:\Development\Django\TestProject\lib\site-packages\django\core\management\base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Development\Django\TestProject\lib\site-packages\django\core\management\commands\migrate.py", line 243, in handle
    post_migrate_state = executor.migrate(
  File "C:\Development\Django\TestProject\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Development\Django\TestProject\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Development\Django\TestProject\lib\site-packages\django\db\migrations\executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Development\Django\TestProject\lib\site-packages\django\db\migrations\migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Development\Django\TestProject\lib\site-packages\django\db\migrations\operations\fields.py", line 236, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "C:\Development\Django\TestProject\lib\site-packages\django\db\backends\base\schema.py", line 571, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type,
  File "C:\Development\Django\TestProject\lib\site-packages\django\db\backends\base\schema.py", line 721, in _alter_field
    self.execute(
  File "C:\Development\Django\TestProject\lib\site-packages\django\db\backends\base\schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "C:\Development\Django\TestProject\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Development\Django\TestProject\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Development\Django\TestProject\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Development\Django\TestProject\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Development\Django\TestProject\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Development\Django\TestProject\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Development\Django\TestProject\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "C:\Development\Django\TestProject\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Development\Django\TestProject\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Development\Django\TestProject\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1101, "BLOB, TEXT, GEOMETRY or JSON column 'description' can't have a default value")
`
```

has this issue been seen, encountered prior and/or any solution found for this?

Cheers!

**Comment by llazzaro** [comment]
Can you give more information about your mysql server?

**Comment by ericjgreen** [comment]
Absolutely. MySQL is running on my desktop (Win10). I have not attempted to deploy anywhere else.

![image](https://user-images.githubusercontent.com/68916571/109313081-6d625180-780d-11eb-9d25-6b4717ba95cd.png)

![image](https://user-images.githubusercontent.com/68916571/109313283-a4d0fe00-780d-11eb-9bf2-11b9995d2bc4.png)

hope this helps.

**Comment by ericjgreen** [comment]
including my ini file for more config details

[my.ini.txt](https://github.com/llazzaro/django-scheduler/files/6050281/my.ini.txt)

**Comment by xsirio** [comment]
I've the same error on mySQL on ubuntu
